#!/bin/sh
# Set up bugzilla and run apache2

MYSQL_HOST=db
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=uniti
MYSQL_DATABASE=bugzilla
MYSQL_USER=mysql
MYSQL_PASSWORD=jai7Paib

cd /opt/bugzilla

# Substitute values into bugzilla localconfig
sed --in-place -f - localconfig <<SED
s/db_host *= *'[a-zA-Z0-9.]\+'/db_host = '${MYSQL_HOST:-$DEFAULT_MYSQL_HOST}'/
s/db_port *= *[0-9.]\+/db_port = ${MYSQL_PORT:-$DEFAULT_MYSQL_PORT}/
s/db_name *= *'[a-zA-Z0-9.]\+'/db_name = '${MYSQL_DATABASE:-$DEFAULT_MYSQL_DATABASE}'/
s/db_user *= *'[a-zA-Z0-9.]\+'/db_user = '${MYSQL_USER:-$DEFAULT_MYSQL_USER}'/
s/db_pass\s*=\s*'[^']*'/db_pass = '${MYSQL_PASSWORD}'/
SED

# Verify bugzilla setup
./checksetup.pl

# Start apache2
. /etc/apache2/envvars

/usr/sbin/apache2 -D FOREGROUND
